build: false
shallow_clone: false
platform: 'x86'

environment:
  matrix:
  - MSYSTEM: MINGW64
    PATH: C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows;%PATH%
  - MSYSTEM: MINGW32
    PATH: C:\msys64\usr\bin;C:\msys64\mingw32\bin;C:\Windows\System32;C:\Windows;%PATH%

install:
  - tests/setup.sh

test_script:
  - tests/unit/helpers/suite.sh