version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            apt-get update
            apt-get install -y curl unzip
            tests/setup.sh
      - run:
          name: Tests
          command: |
             echo Running test
             tests/unit/helpers/suite.sh
