version: 2
jobs:
  apt:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            ./peip-supply setup
            ./peip-supply curl
            ./peip-supply unzip
            ./peip-supply shunit2
      - run:
          name: Tests
          command: |
             echo Running unit tests
             tests/unit/helpers/suite.sh
             echo Running integration tests
             tests/integration/apt/suite.sh
  apk:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            ./peip-supply setup
            ./peip-supply curl
            ./peip-supply unzip
            ./peip-supply shunit2
      - run:
          name: Tests
          command: |
             echo Running integration tests
             tests/integration/apk/suite.sh
  dnf:
    docker:
      - image: fedora
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            ./peip-supply setup
            ./peip-supply curl
            ./peip-supply unzip
            ./peip-supply shunit2
      - run:
          name: Tests
          command: |
             echo Running integration tests
             tests/integration/dnf/suite.sh
  yum:
    docker:
      - image: centos
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            ./peip-supply setup
            ./peip-supply curl
            ./peip-supply unzip
            ./peip-supply shunit2
      - run:
          name: Tests
          command: |
             echo Running integration tests
             tests/integration/yum/suite.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - apt
      - apk
      - dnf
      - yum
