version: 2
jobs:
  apt_integration:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            ./peip-supply setup
            ./peip-supply curl
            ./peip-supply unzip
            ./peip-supply shunit2
      - run:
          name: Tests
          command: |
             echo Running unit tests
             tests/unit/helpers/suite.sh
             echo Running integration tests
             tests/integration/apt/suite.sh
  apk_integration:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            ./peip-supply setup
            ./peip-supply curl
            ./peip-supply unzip
            ./peip-supply shunit2
      - run:
          name: Tests
          command: |
             echo Running unit tests
             tests/unit/helpers/suite.sh
             echo Running integration tests
             tests/integration/apk/suite.sh
  dnf_integration:
    docker:
      - image: fedora
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            ./peip-supply setup
            ./peip-supply curl
            ./peip-supply unzip
            ./peip-supply shunit2
      - run:
          name: Tests
          command: |
             echo Running unit tests
             tests/unit/helpers/suite.sh
             echo Running integration tests
             tests/integration/dnf/suite.sh
  yum_integration:
    docker:
      - image: centos
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            ./peip-supply setup
            ./peip-supply curl
            ./peip-supply unzip
            ./peip-supply shunit2
      - run:
          name: Tests
          command: |
             echo Running unit tests
             tests/unit/helpers/suite.sh
             echo Running integration tests
             tests/integration/yum/suite.sh
  pacman_integration:
    docker:
      - image: base/archlinux
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            ./peip-supply setup
            ./peip-supply curl
            ./peip-supply unzip
            ./peip-supply shunit2
      - run:
          name: Tests
          command: |
             echo Running unit tests
             tests/unit/helpers/suite.sh
             echo Running integration tests
             tests/integration/pacman/suite.sh
  portage_integration:
    docker:
      - image: tharvik/gentoo-portage
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            ./peip-supply setup
            ./peip-supply curl
            ./peip-supply unzip
            ./peip-supply shunit2
      - run:
          name: Tests
          command: |
             echo Running unit tests
             tests/unit/helpers/suite.sh
             echo Running integration tests
             tests/integration/portage/suite.sh
  zypper_integration:
    docker:
      - image: opensuse
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            ./peip-supply setup
            ./peip-supply curl
            ./peip-supply unzip
            ./peip-supply shunit2
      - run:
          name: Tests
          command: |
             echo Running unit tests
             tests/unit/helpers/suite.sh
             echo Running integration tests
             tests/integration/zypper/suite.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - apt_integration
      - apk_integration
      - dnf_integration
      - yum_integration
      - pacman_integration
      - portage_integration
