version: 2
jobs:
  apt:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            apt-get update
            apt-get install -y curl unzip
            tests/setup.sh
      - run:
          name: Tests
          command: |
             echo Running unit tests
             tests/unit/helpers/suite.sh
             echo Running integration tests
             tests/integration/apt/suite.sh
  apk:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            apk update
            apk install curl unzip
            tests/setup.sh
      - run:
          name: Tests
          command: |
             echo Running integration tests
             tests/integration/apk/suite.sh
